# Create a program that imports the math module and uses its functions.

import math

x = 5.6
ans = math.ceil(x)
print(f"The ceil of {x} is: {ans}")

# math.copysign(x,y)
# math.fabs(x)
# math.factorial(x)
# math.floor(x)
# math.gcd(x,y)
# math.fmod(x,y)
# math.frexp(x)
# math.fsum(iterable)
# math.isfinite(x)
# math.isinf(x)
# math.isnan(x)
# math.ldexp(x, i)
# math.modf(x)
# math.trunc(x)
# math.exp(x)
# math.expm1(x)
# math.log(x[,b])
# math.log1p(x)
# math.log2(x)
# math.log10(x)
# math.pow(x,y)
# math.sqrt(x)
# math.acos(x)
# math.asin(x)
# math.atan(x)
# math.cos(x)
# math.hypot(x,y)
# math.sin(x)
# math.tan(x)
# math.degrees(x)
# math.radians(x)
# math.acosh(x)
# math.asinh(x)
# math.atanh(x)
# math.cosh(x)
# math.sinh(x)
# math.tanh(x)
# math.erf(x)
# math.erfc(x)
# math.gamma(x)
# math.lgamma(x)